timezone: America/Los_Angeles
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "*" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
  -
    scope:
      path: ""
    values:
      author: "JGStew"
